name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: windows-latest 
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.201
    
    #Publish dotnet objects
    - name: .NET Publish Web Service
      run: dotnet publish src/DevOpsMetrics.Service/DevOpsMetrics.Service.csproj --configuration Debug --output ${{ github.workspace }}/webservice
    - name: .NET Publish Website
      run: dotnet publish src/DevOpsMetrics.Web/DevOpsMetrics.Web.csproj --configuration Release --output ${{ github.workspace }}/web
    
    - name: .NET Publish functional tests
      run: dotnet publish src/DevOpsMetrics.FunctionalTests/DevOpsMetrics.FunctionalTests.csproj --configuration Release --output ${{ github.workspace }}/functionalTests
    - name: Copy chromedriver for functional test
      run: copy "src/DevOpsMetrics.FunctionalTests/bin/Release/net5.0/chromedriver.exe" "${{ github.workspace }}/functionalTests"
      shell: powershell
    - name: DotNet restore functional tests to get correct NewtonSoft version
      run: dotnet restore src/DevOpsMetrics.FunctionalTests/DevOpsMetrics.FunctionalTests.csproj 
    - name: Copy new NewtonSoft version for functional test
      run: copy "src/DevOpsMetrics.FunctionalTests/bin/Release/net5.0/Newtonsoft.Json.dll" "${{ github.workspace }}/functionalTests"
      shell: powershell
        
    #Publish build artifacts to GitHub
    - name: Upload web service build artifacts back to GitHub
      uses: actions/upload-artifact@v2
      with:
        name: serviceapp
        path: ${{ github.workspace }}/webservice
    - name: Upload website build artifacts back to GitHub
      uses: actions/upload-artifact@v2
      with:
        name: webapp
        path: ${{ github.workspace }}/web

    - name: Upload functional test build artifacts back to GitHub
      uses: actions/upload-artifact@v2
      with:
        name: functionaltests
        path: ${{ github.workspace }}/functionalTests
    - name: Upload probot build artifacts back to GitHub
      uses: actions/upload-artifact@v2
      with:
        name: probot
        path: src/ProbotMetrics


  test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.201
    #Run automated .NET tests   
    - name: Variable Substitution appsettings file for tests
      uses: microsoft/variable-substitution@v1
      with:
        files: 'src/DevOpsMetrics.Tests/appsettings.json'
      env:
        AppSettings.AzureDevOpsPatToken: "${{ secrets.AzureDevOpsPATToken }}"
        AppSettings.GitHubClientId: "${{ secrets.GitHubClientId }}" 
        AppSettings.GitHubClientSecret: "${{ secrets.GitHubClientSecret }}" 
        AppSettings.AzureStorageAccountConfigurationString: "${{ secrets.AzureStorageConnectionString }}" 
        AppSettings.KeyVaultClientId: "${{ secrets.KeyVaultClientId }}" 
        AppSettings.KeyVaultClientSecret: "${{ secrets.KeyVaultClientSecret }}" 
    - name: view appsettings file after substitution
      run: Get-Content -Path "src/DevOpsMetrics.Tests/appsettings.json"
    - name: Run automated unit and integration tests
      run: dotnet test src/DevOpsMetrics.Tests/DevOpsMetrics.Tests.csproj --configuration Debug --logger trx /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov --settings:./src/DevOpsMetrics.Tests/CodeCoverage.runsettings 
    - name: Publish coverage report to coveralls.io
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: src/DevOpsMetrics.Tests/TestResults/coverage.info 


  buildFunction:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.407
    - name: .NET Publish Function
      run: dotnet publish src/DevOpsMetrics.Function/DevOpsMetrics.Function.csproj --configuration Debug --output ${{ github.workspace }}/function 
    - name: Upload function build artifacts back to GitHub
      uses: actions/upload-artifact@v2
      with:
        name: functionapp
        path: ${{ github.workspace }}/function


  #Disabling PROBOT for 2021 reboot to focus on website
  #Deploy the probot artifacts to Azure
#  deployProbot:
#    runs-on: ubuntu-latest
#    needs: build    
#    #if: github.ref == 'refs/heads/main'    
#    if: 0 == 1 #Disabling PROBOT for 2021 reboot to focus on website
#    steps:        
#    # Login with the secret SP details
#    - name: Log into Azure
#      uses: azure/login@v1
#      with:
#        creds: ${{ secrets.AZURE_SP_PROBOT }}  
#    - name: Download webapp artifact
#      uses: actions/download-artifact@v1.0.0
#      with:
#        name: probot 
#    - name: Deploy probot to Azure WebApp
#      uses: Azure/webapps-deploy@v1
#      with:
#        app-name: devopsmetrics-prod-eu-probot
#        package: probot 
#    - name: Deploy probot app settings
#      run: az webapp config appsettings set --name devopsmetrics-prod-eu-probot --resource-group "DevOpsMetricsProbot" --settings SCM_DO_BUILD_DURING_DEPLOYMENT=true


  #Deploy the artifacts to Azure staging slots
  deployToStagingSlots:
    runs-on: windows-latest
    needs: 
    - build      
    - test
    - buildFunction
    steps:        
    # Login with the secret SP details
    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SP }}  
    
    #Download the artifacts from GitHub
    - name: Download serviceapp artifact
      uses: actions/download-artifact@v1.0.0
      with:
        name: serviceapp 
    - name: Download webapp artifact
      uses: actions/download-artifact@v1.0.0
      with:
        name: webapp 
    - name: Download webapp artifact
      uses: actions/download-artifact@v1.0.0
      with:
        name: functionapp    
    - name: Download functionaltests artifact
      uses: actions/download-artifact@v1.0.0
      with:
        name: functionaltests

    #Deploy service, website, and function to Azure
    - name: Deploy web service to Azure WebApp
      uses: Azure/webapps-deploy@v1
      with:
        app-name: devopsmetrics-prod-eu-service
        package: serviceapp
        slot-name: staging 
    - name: Deploy web service app settings
      run: az webapp config appsettings set --name "devopsmetrics-prod-eu-service" --slot "staging" --resource-group "devopsmetrics" --settings "AppSettings:AzureDevOpsPatToken=${{ secrets.AzureDevOpsPATToken }}" "AppSettings:GitHubClientId=${{ secrets.GitHubClientId }}" "AppSettings:GitHubClientSecret=${{ secrets.GitHubClientSecret }}"  "AppSettings:AzureStorageAccountConfigurationString=${{ secrets.AzureStorageConnectionString }}" "AppSettings:KeyVaultClientId=${{ secrets.KeyVaultClientId }}" "AppSettings:KeyVaultClientSecret=${{ secrets.KeyVaultClientSecret }}" 
    
    - name: Deploy website to Azure WebApp
      uses: Azure/webapps-deploy@v1
      with:
        app-name: devopsmetrics-prod-eu-web
        package: webapp 
        slot-name: staging         
    - name: Deploy website app settings
      run: az webapp config appsettings set --name devopsmetrics-prod-eu-web --slot "staging" --resource-group "devopsmetrics" --settings "AppSettings:AzureDevOpsPatToken=${{ secrets.AzureDevOpsPATToken }}" "AppSettings:GitHubClientId=${{ secrets.GitHubClientId }}" "AppSettings:GitHubClientSecret=${{ secrets.GitHubClientSecret }}"  

    # Run functional tests on staging slots
    - name: Functional Tests
      run: |
        $vsTestConsoleExe = "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\Common7\\IDE\\Extensions\\TestPlatform\\vstest.console.exe"
        $targetTestDll = "functionaltests\DevOpsMetrics.FunctionalTests.dll"
        $testRunSettings = "/Settings:`"functionaltests\test.runsettings`" "
        $parameters = " -- ServiceUrl=""https://devopsmetrics-prod-eu-service-staging.azurewebsites.net/"" WebsiteUrl=""https://devopsmetrics-prod-eu-web-staging.azurewebsites.net/"" "
        #Note that the `" is an escape character to quote strings, and the `& is needed to start the command
        $command = "`& `"$vsTestConsoleExe`" `"$targetTestDll`" $testRunSettings $parameters " 
        Write-Host "$command"
        Invoke-Expression $command
      shell: powershell
    
    # deploy function and settings
    - name: Deploy function to Azure WebApp
      uses: Azure/webapps-deploy@v1
      with:
        app-name: devopsmetrics-prod-eu-function
        package: functionapp 
    - name: Deploy function app settings
      run: az webapp config appsettings set --name "devopsmetrics-prod-eu-function" --resource-group "devopsmetrics" --settings "AppSettings:AzureDevOpsPatToken=${{ secrets.AzureDevOpsPATToken }}" "AppSettings:GitHubClientId=${{ secrets.GitHubClientId }}" "AppSettings:GitHubClientSecret=${{ secrets.GitHubClientSecret }}" "AppSettings:AzureStorageAccountConfigurationString=${{ secrets.AzureStorageConnectionString }}" "AppSettings:WebServiceURL=https://devopsmetrics-prod-eu-service.azurewebsites.net/" 


  swapDeploymentSlots:
    runs-on: ubuntu-latest # Note, Azure CLI requires a Linux runner...
    needs: [build, deployToStagingSlots]
    #Only swap from staging to production slots if running off the main branch - we don't want to deploy off feature branches/PRs
    if: github.ref == 'refs/heads/main'     
    steps:
    # Login with the secret SP details
    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SP }}     
      #Swap staging slots with prod
    - name: Swap web service staging slot to production
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: az webapp deployment slot swap --name "devopsmetrics-prod-eu-service" --resource-group "devopsmetrics" --slot staging --target-slot production
    - name: Deploy web service app settings
      run: az webapp config appsettings set --name "devopsmetrics-prod-eu-service" --resource-group "devopsmetrics" --settings "AppSettings:AzureDevOpsPatToken=${{ secrets.AzureDevOpsPATToken }}" "AppSettings:GitHubClientId=${{ secrets.GitHubClientId }}" "AppSettings:GitHubClientSecret=${{ secrets.GitHubClientSecret }}" "AppSettings:AzureStorageAccountConfigurationString=${{ secrets.AzureStorageConnectionString }}"     
    - name: Swap web site staging slot to production
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: az webapp deployment slot swap --name "devopsmetrics-prod-eu-web" --resource-group "devopsmetrics" --slot staging --target-slot production
    - name: Deploy website app settings
      run: az webapp config appsettings set --name devopsmetrics-prod-eu-web --resource-group "devopsmetrics" --settings "AppSettings:AzureDevOpsPatToken=${{ secrets.AzureDevOpsPATToken }}" "AppSettings:GitHubClientId=${{ secrets.GitHubClientId }}" "AppSettings:GitHubClientSecret=${{ secrets.GitHubClientSecret }}"  







#  #Publish the Azure DevOps extension (Currently disabled)
#  deployAzureDevOpsExtension:
#    runs-on: windows-latest
#    needs: [build, swapDeploymentSlots]
#    if: 1==0 # Commented out/skipping this job for now   
#    env:
#      extensionVersion: "0.0.0" 
#    #if: github.ref == 'refs/heads/main'
#    steps:
#    - uses: actions/checkout@v2
#    - name: Setup .NET Core
#      uses: actions/setup-dotnet@v1
#      with:
#        dotnet-version: 3.1.101
#    - name: .NET core Publish Azure DevOps Extension
#      run: dotnet publish src/DevOpsMetrics.AzureDevOpsExtension/DevOpsMetrics.AzureDevOpsExtension.csproj --configuration Release   
#    - name: Build extension
#      run: |
#        npm install -g tfx-cli
#        tfx extension create --manifest-globs vss-extension.json --root src\DevOpsMetrics.AzureDevOpsExtension\bin\Release\netcoreapp3.1\publish\wwwroot --output-path src\DevOpsMetrics.AzureDevOpsExtension\bin\Release\netcoreapp3.1\publish\wwwroot  #--rev-version
#        #tfx extension samsmithnz create --token "${{ secrets.AzureDevOpsPATToken }}"
#        #tfx extension publish --help 
#    - name: Check files
#      run: |
#        cd src\DevOpsMetrics.AzureDevOpsExtension\bin\Release\netcoreapp3.1\publish\wwwroot
#        dir
#        Write-Host "New env variable " ${{ env.extensionVersion }}
#    - name: Upload Azure DevOps extension build artifacts back to GitHub
#      uses: actions/upload-artifact@v2
#      with:
#        name: azuredevopsextensionpackage
#        path: src\DevOpsMetrics.AzureDevOpsExtension\bin\Release\netcoreapp3.1\publish\wwwroot\SamSmithNZ.high-performing-devops-metrics-${{ env.extensionVersion }}.vsix
